---
# Satisfactory handlers

- name: Reload systemctl
  ansible.builtin.command: systemctl daemon-reload

- name: Restart Satisfactory service
  ansible.builtin.service:
    name: satisfactory
    state: restarted
