---
# Common tasks for all hosts

- name: Include user management tasks
  ansible.builtin.import_tasks: user.yml

- name: Include system update tasks
  ansible.builtin.import_tasks: update.yml

- name: Include network configuration tasks
  ansible.builtin.import_tasks: network.yml
  tags:
    - network
