---
# User management tasks

- name: Install ACL
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes

- name: Install ssh key
  ansible.posix.authorized_key:
    comment: Managed via ansible
    exclusive: yes
    key: "{{ admin_ssh_key }}"
    user: "{{ ansible_user }}"

- name: Set user password
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ password }}"
  when: password is defined

- name: Configure passwordless sudo
  community.general.sudoers:
    commands: ALL
    name: "{{ ansible_user }}"
    user: "{{ ansible_user }}"
