---
# Main playbook that includes all other playbooks

- name: Apply common configuration to all hosts
  hosts: all
  roles:
    - common

- name: Configure Home Assistant server
  import_playbook: ha-deploy.yml

- name: Configure ESPHome server
  import_playbook: esphome.yml

- name: Configure game server
  import_playbook: game_server.yml

- name: Configure DNS servers
  import_playbook: dns.yml

- name: Include Tailscale role
  hosts: all
  roles:
    - tailscale
